### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'name'

### ISSUE THREAD

**Issue by 13-Strings** [HarryShomer/LPFormer#3]
Hello, I want to reproduce your article code. The virtual environment with the required package has been configured, but after the configuration, there are the following errors when running the code, which seems to be the problem of the code itself. Could you please advise me whether there is any problem in my understanding, and what aspects should I take to solve the problem and successfully reproduce it? Thank you very much!

$ python src/run.py --data_name pubmed --lr 1e-3  --gnn-layers 1 --dim 128 --batch-size 1024  --epochs 100 --eps 1e-5 --gnn-drop 0.3 --dropout 0.3 --pred-drop 0.3 --att-drop 0.3  --num-heads 1  --thresh-1hop 1e-2 --thresh-non1hop 1e-2 --mask-input  --feat-drop 0.3 --l2 1e-4 --eval_steps 1 --decay 1 --non-verbose --runs 10 --device 0
 of nodes in pubmed is:  19717
Calculating PPR...
Traceback (most recent call last):
  File "/home/zhangc/workspace/LPFormer/src/run.py", line 280, in <module>
    main()
  File "/home/zhangc/workspace/LPFormer/src/run.py", line 276, in main
    run_model(args)
  File "/home/zhangc/workspace/LPFormer/src/run.py", line 160, in run_model
    data = read_data_planetoid(cmd_args, device)
  File "/home/zhangc/workspace/LPFormer/src/util/read_datasets.py", line 239, in read_data_planetoid
    data['ppr'] = get_ppr(args.data_name, data['edge_index'], data['num_nodes'],
  File "/home/zhangc/workspace/LPFormer/src/util/calc_ppr_scores.py", line 263, in get_ppr
    neighbors, neighbor_weights = get_ppr_matrix(edge_index, num_nodes, alpha, eps)
  File "/home/zhangc/workspace/LPFormer/src/util/calc_ppr_scores.py", line 121, in get_ppr_matrix
    neighbors, neighbor_weights = get_calc_ppr()(indptr, edge_index_np[1], out_degree, alpha, eps)
  File "/home/zhangc/ENTER/envs/LPFormer1/lib/python3.9/site-packages/numba/core/dispatcher.py", line 442, in _compile_for_args
    raise e
  File "/home/zhangc/ENTER/envs/LPFormer1/lib/python3.9/site-packages/numba/core/dispatcher.py", line 375, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "/home/zhangc/ENTER/envs/LPFormer1/lib/python3.9/site-packages/numba/core/dispatcher.py", line 905, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/zhangc/ENTER/envs/LPFormer1/lib/python3.9/site-packages/numba/core/dispatcher.py", line 80, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/home/zhangc/ENTER/envs/LPFormer1/lib/python3.9/site-packages/numba/core/dispatcher.py", line 94, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/zhangc/ENTER/envs/LPFormer1/lib/python3.9/site-packages/numba/core/dispatcher.py", line 107, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/home/zhangc/ENTER/envs/LPFormer1/lib/python3.9/site-packages/numba/core/compiler.py", line 744, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/zhangc/ENTER/envs/LPFormer1/lib/python3.9/site-packages/numba/core/compiler.py", line 438, in compile_extra
    return self._compile_bytecode()
  File "/home/zhangc/ENTER/envs/LPFormer1/lib/python3.9/site-packages/numba/core/compiler.py", line 506, in _compile_bytecode
    return self._compile_core()
  File "/home/zhangc/ENTER/envs/LPFormer1/lib/python3.9/site-packages/numba/core/compiler.py", line 481, in _compile_core
    raise e
  File "/home/zhangc/ENTER/envs/LPFormer1/lib/python3.9/site-packages/numba/core/compiler.py", line 472, in _compile_core
    pm.run(self.state)
  File "/home/zhangc/ENTER/envs/LPFormer1/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 364, in run
    raise e
  File "/home/zhangc/ENTER/envs/LPFormer1/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/home/zhangc/ENTER/envs/LPFormer1/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/zhangc/ENTER/envs/LPFormer1/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/zhangc/ENTER/envs/LPFormer1/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
  File "/home/zhangc/ENTER/envs/LPFormer1/lib/python3.9/site-packages/numba/core/typed_passes.py", line 468, in run_pass
    lower.lower()
  File "/home/zhangc/ENTER/envs/LPFormer1/lib/python3.9/site-packages/numba/core/lowering.py", line 187, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/zhangc/ENTER/envs/LPFormer1/lib/python3.9/site-packages/numba/core/lowering.py", line 226, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/zhangc/ENTER/envs/LPFormer1/lib/python3.9/site-packages/numba/core/lowering.py", line 256, in lower_function_body
    self.lower_block(block)
  File "/home/zhangc/ENTER/envs/LPFormer1/lib/python3.9/site-packages/numba/core/lowering.py", line 270, in lower_block
    self.lower_inst(inst)
  File "/home/zhangc/ENTER/envs/LPFormer1/lib/python3.9/site-packages/numba/parfors/parfor_lowering.py", line 51, in lower_inst
    _lower_parfor_parallel(self, inst)
  File "/home/zhangc/ENTER/envs/LPFormer1/lib/python3.9/site-packages/numba/parfors/parfor_lowering.py", line 67, in _lower_parfor_parallel
    return _lower_parfor_parallel_std(lowerer, parfor)
  File "/home/zhangc/ENTER/envs/LPFormer1/lib/python3.9/site-packages/numba/parfors/parfor_lowering.py", line 349, in _lower_parfor_parallel_std
    exp_name_to_tuple_var) = _create_gufunc_for_parfor_body(
  File "/home/zhangc/ENTER/envs/LPFormer1/lib/python3.9/site-packages/numba/parfors/parfor_lowering.py", line 1500, in _create_gufunc_for_parfor_body
    hoisted, not_hoisted = hoist(parfor_params, loop_body, typemap, wrapped_blocks)
  File "/home/zhangc/ENTER/envs/LPFormer1/lib/python3.9/site-packages/numba/parfors/parfor_lowering.py", line 975, in hoist
    find_setitems_body(setitems, itemsset, loop_body, typemap)
  File "/home/zhangc/ENTER/envs/LPFormer1/lib/python3.9/site-packages/numba/parfors/parfor_lowering.py", line 950, in find_setitems_body
    find_setitems_block(setitems, itemsset, block, typemap)
  File "/home/zhangc/ENTER/envs/LPFormer1/lib/python3.9/site-packages/numba/parfors/parfor_lowering.py", line 936, in find_setitems_block
    if getattr(typemap[item.name], "mutable", False):
AttributeError: 'tuple' object has no attribute 'name'

**Comment by 13-Strings** [comment]
Amazingly, the numba package used for acceleration can be turned off, so that it seems to solve the above error.
